using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Huml.Net.SourceGeneration;

/// <summary>
/// Incremental source generator for Huml.Net. For each type registered via
/// <c>[HumlSerializable(typeof(T))]</c> on a <c>HumlGeneratedContext</c> subclass,
/// emits a concrete <c>HumlTypeInfo&lt;T&gt;</c> and the corresponding dispatch override.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class HumlSerializationGenerator : IIncrementalGenerator
{
    private const string AttributeFqn =
        "Huml.Net.Serialization.Attributes.HumlSerializableAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contextModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => TransformContext(ctx))
            .Where(static m => m.HasValue)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(contextModels,
            static (spc, model) => EmitSource(spc, model));
    }

    private static ContextModel? TransformContext(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol contextSymbol)
            return null;

        var types = new List<TypeModel>();

        foreach (var attr in ctx.Attributes)
        {
            if (attr.ConstructorArguments.Length == 0) continue;
            if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol typeSymbol) continue;

            // Walk the type hierarchy from base to derived so properties appear base-first
            // (matching the reflection path's declaration-order convention). This ensures
            // derived types include inherited properties without the serialiser needing to
            // chain multiple TypeInfo lookups.
            var hierarchy = new List<INamedTypeSymbol>();
            var current = typeSymbol;
            while (current != null && current.SpecialType != SpecialType.System_Object)
            {
                hierarchy.Add(current);
                current = current.BaseType;
            }
            hierarchy.Reverse();

            var seen = new HashSet<string>(StringComparer.Ordinal);
            var properties = new List<PropertyModel>();
            foreach (var t in hierarchy)
            {
                var declaringFqn = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                foreach (var member in t.GetMembers())
                {
                    if (member is not IPropertySymbol prop) continue;
                    if (prop.DeclaredAccessibility != Accessibility.Public) continue;
                    if (prop.IsStatic || prop.IsIndexer || prop.IsAbstract) continue;
                    if (!seen.Add(prop.Name)) continue; // skip overrides / hidden properties

                    var canGet = prop.GetMethod?.DeclaredAccessibility == Accessibility.Public;
                    var canSet = prop.SetMethod?.DeclaredAccessibility == Accessibility.Public
                              || prop.SetMethod?.IsInitOnly == true;

                    if (!canGet) continue;

                    properties.Add(new PropertyModel(
                        prop.Name,
                        prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        canGet,
                        canSet,
                        declaringFqn));
                }
            }

            var fqn = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            types.Add(new TypeModel(typeSymbol.Name, fqn,
                new EquatableArray<PropertyModel>(properties.ToArray())));
        }

        if (types.Count == 0) return null;

        var ns = contextSymbol.ContainingNamespace.IsGlobalNamespace ? ""
            : contextSymbol.ContainingNamespace.ToDisplayString();

        return new ContextModel(contextSymbol.Name, ns,
            new EquatableArray<TypeModel>(types.ToArray()));
    }

    private static void EmitSource(SourceProductionContext spc, ContextModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment — generated code");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName}");
        sb.AppendLine("{");

        sb.AppendLine($"    public static {model.ClassName} Default {{ get; }} = new {model.ClassName}();");
        sb.AppendLine();

        foreach (var type in model.Types.ToArray())
        {
            sb.AppendLine($"    public global::Huml.Net.Serialization.HumlTypeInfo<{type.FullyQualifiedName}> {type.Name} {{ get; }}");
            sb.AppendLine($"        = new {type.Name}HumlTypeInfo();");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine($"    public override global::Huml.Net.Serialization.HumlTypeInfo? GetTypeInfo(global::System.Type type, global::Huml.Net.Versioning.HumlOptions options)");
        sb.AppendLine("    {");
        foreach (var type in model.Types.ToArray())
            sb.AppendLine($"        if (type == typeof({type.FullyQualifiedName})) return {type.Name};");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");

        foreach (var type in model.Types.ToArray())
        {
            sb.AppendLine();
            EmitTypeInfoClass(sb, type);
        }

        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}.Huml.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitTypeInfoClass(StringBuilder sb, TypeModel type)
    {
        sb.AppendLine($"    private sealed class {type.Name}HumlTypeInfo : global::Huml.Net.Serialization.HumlTypeInfo<{type.FullyQualifiedName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        private static readonly global::System.Collections.Generic.IReadOnlyList<global::Huml.Net.Serialization.HumlPropertyInfo> _properties");
        sb.AppendLine("            = new global::Huml.Net.Serialization.HumlPropertyInfo[]");
        sb.AppendLine("            {");

        foreach (var prop in type.Properties.ToArray())
        {
            sb.Append("                new() {");
            sb.Append($" Name = \"{prop.Name}\",");
            sb.Append($" PropertyType = typeof({prop.TypeName}),");
            if (prop.HasGet)
                sb.Append($" Get = static o => (({prop.DeclaringTypeFqn})o).{prop.Name},");
            if (prop.HasSet)
                sb.Append($" Set = static (o, v) => (({prop.DeclaringTypeFqn})o).{prop.Name} = ({prop.TypeName})v!,");
            sb.AppendLine(" },");
        }

        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine($"        public override global::System.Collections.Generic.IReadOnlyList<global::Huml.Net.Serialization.HumlPropertyInfo> Properties => _properties;");
        sb.AppendLine();
        sb.AppendLine($"        public override global::System.Func<{type.FullyQualifiedName}>? CreateObject => static () => new {type.FullyQualifiedName}();");
        sb.AppendLine("    }");
    }
}
